config/routes.rb
Rails.application.routes.draw do

  get 'downgrade' => 'users#downgrade', :as => :downgrade

  devise_for :users

  resources :users, :only => [:show]

  resources :wikis do
    resources :collaborations, only: [:create, :destroy]
  end

  resources :charges, only: [:new, :create]

  root 'users#show'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis, dependent: :destroy
  has_many :collaborations, dependent: :destroy

  after_initialize :init
  after_update :downgrade_wikis

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  attr_accessor :login

  enum role: [:standard, :premium, :admin]

  def admin?
    role == 'admin'
  end

  def premium?
    role == 'premium'
  end

  def standard?
    role == 'standard'
  end

  def owner_of_wiki?(wiki)
    wiki.user == self
  end

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(email).downcase # rubocop:disable Style/ColonMethodCall
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def self.find_for_database_authentication(warden_conditions) # rubocop:disable Metrics/AbcSize
    conditions = warden_conditions.dup
    if login == conditions.delete(:login)
      where(conditions.to_h).find_by(["lower(username) = :value OR lower(email) = :value", { value: login.downcase }])
    elsif conditions.key?(:username) || conditions.key?(:email)
      conditions[:email].downcase! if conditions[:email]
      find_by(conditions.to_h)
    end
  end

  private

  def init
    return unless new_record? && role.nil?

    self.role = 'standard'
  end

  def downgrade_wikis
    return unless role_changed?(from: 'premium', to: 'standard')
    wikis.update_all private: false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def downgrade
    flash[:notice] = "You have successfully downgraded your account. Your Private Wikis will be made Public."
    current_user.update_attribute(:role, 'standard')
    redirect_to wikis_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/downgrade.html.erb
<%= link_to "Downgrade", :controller => :users, :action => :downgrade, class: 'btn btn-danger', :method => :patch %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="media">
      <br />
      <% avatar_url = @user.avatar_url(128) %>
      <% if avatar_url %>
        <div class="media-left">
          <%= image_tag avatar_url, class: 'media-object' %>
        </div>
      <% end %>
      <div class="media-body">
        <h2 class="media-heading">Profile Information</h2>
        <h4 class="media-heading">Your E-mail: <%= @user.email %></h4>
        <h4 class="media-heading">Your Username: <%= @user.username %></h4>
        <h4 class="media-heading">Membership Status: <%= @user.role %></h4>
        <h4 class="media-heading">
          <div class="col-md-4">
            <% if user_signed_in? && current_user.standard? %>
              <%= link_to "Upgrade Account", new_charge_path, class: 'btn btn-success' %>
            <% else user_signed_in? && current_user.premium? %>
              <%= link_to "Downgrade Account", downgrade_path, class: 'btn btn-success', data: {confirm: 'Standard Accounts have no Private Wikis. If you downgrade, your Private Wikis will be made Public.'} %>
            <% end %>
          </div >
        </h4>
      </div>
    </div>
  </div>
</div>

<h2>Create a New Wiki</h2>
<%= render partial: 'wikis/form', locals: { user: @user, wiki: Wiki.new } %>

<% if current_user.wikis.exists? %>
<h2>Your Wikis</h2>
<%= render @user.wikis %>
<% end %>

<% if current_user.collaborations.exists? %>
<h2>Private Collaborations</h2>
  <% @user.collaborations.each do |collaboration| %>
    <tr>
        <td><%= link_to collaboration.wiki.title, collaboration.wiki %></td>
    </tr>
  <% end %>
<% end %>