config/routes.rb
Rails.application.routes.draw do

  get 'downgrade' => 'users#downgrade', :as => :downgrade

  devise_for :users

  resources :users, :only => [:show]

  resources :wikis do
    resources :collaborations, only: [:create, :destroy]
  end

  resources :charges, only: [:new, :create]

  root 'users#show'

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations, dependent: :destroy
  has_many :users, through: :collaborations

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 5 }, presence: true

  default_scope { order('updated_at DESC') }

  after_update :delete_collaborations

  #  scope :visible_to, -> (user) { user ? all : where(private: false) }

  private

  def delete_collaborations
    return unless private == false

    collaborations.delete_all
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  include Pundit

  before_action :authenticate_user!, except: [:index, :show]

  #  after_action :verify_authorized, except: :index
  #  after_action :verify_policy_scoped, only: :index

  def index
    @wikis = policy_scope(Wiki)
    authorize @wiki
  end

  def show
    @wiki = Wiki.find(params[:id])
    @user = current_user
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was saved successfully"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the Wiki. Please try again."
      render :new
    end
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def edit
    @user = current_user
    @users = User.all
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was updated successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    # title = @wiki.title

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
<% if policy(@wiki).new? %>
<%= form_for @wiki do |f| %>
  <% if wiki.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
      <ul>
        <% wiki.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for @wiki do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter Title here" %>
    </div>

    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_field :body, class: 'form-control', placeholder: "Enter Info here" %>
    </div>

    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>

    <% if current_user.admin? || current_user.premium? %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
        <% end %>
      </div>

    <% end %>
  <% end %>
<% end %>
<% end %>

app/views/wikis/_wiki.html.erb
<div class="media">
  <div class="media-body">
    <h3 class="media-heading">
      <%= link_to wiki.title, wiki_path(wiki) %>
    </h3>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wikis</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for Wikis</p>
    <ul>
      <li>Input info into both the title and body fields</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
      <% if @wiki.private? && (current_user.admin? || current_user.owner_of_wiki?(@wiki)) %>
        <%= render partial: "collaborations/form", locals: {wiki: @wiki, user: @user} %>
      <% end %>

    <% if @wiki.private %>
      <% if Collaboration.exists?(wiki_id: @wiki) %>
      <%= render partial: 'collaborations/collaborations', locals: { wiki: @wiki } %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.title, wiki %>
          </h4>
          <small>
            Created <%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.user.username %>
          </small>
        </div>
      </div>
    <% end %>
  </div>

  <% if policy(@wiki).new? %>
    <div class="col-md-4">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    </div >
  <% end %>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Input info into both the title and body fields</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/show.html.erb
<div>
  <h1>
    <%= markdown(@wiki.title) %> <br>
    <h5>
    <small>
      submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.email %>
    </small>
    </h5>
  </h1>
</div>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  <div class="col-md-4">
    <% if policy(@wiki).edit? %>
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <% end %>
    <% if policy(@wiki).destroy? %>
    <%= link_to "Delete Wiki", [@wiki], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
    <% end %>
  </div>
  </div>


  <% if @wiki.private? && (current_user.admin? || current_user.owner_of_wiki?(@wiki)) %>
    <%= render partial: "collaborations/form", locals: {wiki: @wiki, user: @user} %>
  <% end %>



  <% if @wiki.private %>
    <% if Collaboration.exists?(wiki_id: @wiki) %>
    <%= render partial: 'collaborations/collaborations', locals: { wiki: @wiki } %>
    <% end %>
  <% end %>