config/routes.rb
Rails.application.routes.draw do

  get 'downgrade' => 'users#downgrade', :as => :downgrade

  devise_for :users

  resources :users, :only => [:show]

  resources :wikis do
    resources :collaborations, only: [:create, :destroy]
  end

  resources :charges, only: [:new, :create]

  root 'users#show'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Profile", root_path %></li>
      <li><%= link_to "All Wikis", wikis_path %></li>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <div class="pull-right user-info">
      <% if user_signed_in? %>
      <%= image_tag current_user.avatar_url(48), class: "gravatar" %>
      <div class="pull-right">
      <%= link_to "Edit Profile", edit_user_registration_path, :class => 'navbar-link' %> or
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
      </div>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> or
      <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
    <% end %>
    </div>
  </ul>

  <%= yield %>
  </div>

</body>
</html>